### ISSUE TITLE
Slightly more performant method

### ISSUE THREAD

**Issue by wesleytodd** [hughsk/clamp#5]
http://jsperf.com/clamp-functions/19

Not entirely sure it matters, but I found this js perf and added your method to it.  I can do the PR for this if you are interested.

``` javascript
function clamp(value, min, max) {
  return value < min ? min : value > max ? max : value;
}
```

**Comment by hediyi** [comment]
what if `min` > `max`?

**Comment by wesleytodd** [comment]
To be honest I don't even remember opening this issue, or why I did.  Closing.
